---
abstract: 'Convenient and fast Dropbox API abstraction'
author:
  - 'Alexander Nazarov <nfokz@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Dropbox
provides:
  File::Dropbox:
    file: lib/File/Dropbox.pm
    version: 0.3
requires:
  JSON: 2.0
  Net::Curl: 0.28
resources:
  license: http://dev.perl.org/licenses/
version: 0.3
